config/routes.rb
Admission::Application.routes.draw do
  root  'static_pages#home'
  match '/about',   to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  resources :students do
    resources :educations
  end

end

app/models/education.rb
class Education < ActiveRecord::Base
  belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
  has_one :education

  validates :name, :email, :gender, :contact, :birth_date, :address, :city, :state, :pincode, presence: true
  validates :name,:father_name,:mother_name, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :contact, length: { is: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  def new
    @student = Student.find(params[:student_id])
    @education = @student.build_education
  end
  
  def create
    @student = Student.find(params[:student_id])
    @education = @student.create_education(education_params)
    if @education.save
      redirect_to student_education_path(@student, @education)
    else
      render 'new'
    end
  end

  def show
    @student = Student.find(params[:student_id])
    @education = @student.education
  end

  private
  def education_params
    params.require(:education).permit(:student_id, :tenth_board, :tenth_school_name, :tenth_percentage, :twelvth_board, :twelvth_school_name, :twelvth_percentage, :entrance_rank)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  
  def contact
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def new
    @student = Student.new
  end

  def create
    @student = Student.create(student_params)
    if @student.save
      redirect_to new_student_education_path(@student)
    else
      render 'new'
    end
  end

  def show
    @student = Student.find(params[:id])
  end
  
  private
  def student_params
    params.require(:student).permit(:name, :email, :gender, :birth_date, :father_name, :mother_name, :contact, :address, :city, :state, :pincode)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
 def full_title(page_title)
    base_title = "SK MEMORIAL ADMISSION PROCEDURE"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/views/educations/new.html.erb
<h1>Academics Details</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for [@student, @education] do |f| %>
      <%= f.label :tenth_board %>
      <%= f.text_field :tenth_board %>
   
      <%= f.label :tenth_school_name %>
      <%= f.text_field :tenth_school_name %>

      <%= f.label :tenth_percentage %>
      <%= f.number_field :tenth_percentage %>

      <%= f.label :twelvth_board %>
      <%= f.text_field :twelvth_board %>

      <%= f.label :twelvth_school_name %>
      <%= f.text_field :twelvth_school_name %>

      <%= f.label :twelvth_percentage %>
      <%= f.number_field :twelvth_percentage %>
      
      <%= f.label :entrance_rank %>
      <%= f.number_field :entrance_rank %><br>
    
      <%= f.submit "Next Page", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/educations/show.html.erb
<h1>show page</h1>
<%= @education.tenth_board %>
<%= @education.tenth_school_name %>
<%= @education.tenth_percentage %>
<%= @education.twelvth_board %>
<%= @education.twelvth_school_name %>
<%= @education.twelvth_percentage %>
<%= @education.entrance_rank %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to "SK Memorial", "http://skmemorial.org" %>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <h5>SK MEMORIAL </h5>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Members Area", '#' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @student.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@student.errors.count, "error") %>.
    </div>
    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About Us </h1>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>
<h1>Contact Us </h1>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>ADMISSION PROCEDURE</h1>
  <%= link_to "Register new Applicants", new_student_path, class: "btn btn-large btn-primary" %>
</div>
<p><center>
    Click here to know about the admission procedure guidelines.
    <%= link_to  "Admission procesedure guidelines","http://kvsanghatan.nic.in/" %>
</p></center>

app/views/students/new.html.erb
<% provide(:title, 'Basic Details') %>
<h1>REGISTRATION FORM</h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for(@student) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %><br>

      <%= f.label :Gender, class: "gender" %>
      <%= f.label :Gender, "Female",class: "gender" %>
      <%= f.radio_button :gender,  "female" %>
      <%= f.label :Gender, "Male", class: "gender" %>
      <%= f.radio_button :gender, "male" %>
     
      <%= f.label :birth_date %>
      <%= f.date_field :birth_date %>

      <%= f.label :father_name %>
      <%= f.text_field :father_name %>

      <%= f.label :mother_name %>
      <%= f.text_field :mother_name %>

      <%= f.label :Contact %>
      <%= f.text_field :contact %>

      <%= f.label :Address %>
      <%= f.text_field :address %>

      <%= f.label :City %>
      <%= f.text_field :city %>

      <%= f.label :State %>
      <%= f.text_field :state %>

      <%= f.label :Pincode %>
      <%= f.text_field :pincode %><br>

      <%= f.submit "Next Page", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/students/show.html.erb
<%= @student.name %>
<%= @student.email %>
<%= @student.gender %>
<%= @student.birth_date %>
<%= @student.father_name %>
<%= @student.mother_name %>
<%= @student.contact %>
<%= @student.address %>
<%= @student.city %>
<%= @student.state %>
<%= @student.pincode %>